### PR TITLE
feat: Upgrade cozy dependencies for App Amirale navigation

### PR DESCRIPTION
**Pull request by acezard**
- Updating cozy-bar for localdev purposes
- Inject webviewIntent into BarContextProvider because ActionMenu doesn't have access to the webviewIntent from the cozy-bar directly
- Still need to update cozy-ui once it's published

### CODE REVIEW

**Comment by trollepierre** [comment]
could you rebase please? I think you didn't add +270kb in the bundle

**Comment by acezard** [comment]
> could you rebase please? I think you didn't add +270kb in the bundle.
> 
> Then can you check the delta from bundlemon before merge? If delta < 1%, ok.

I'm up to date with master according to git

**Comment by trollepierre** [comment]
> edit: it has to be the cozybar update (only used in localhost here)

If cozybar is only used in localhost, it should not be in the bundle. :(

**Comment by trollepierre** [comment]
Upgrade of cozy-bar@7.17.

responsible of 

```
app/drive.(hash).js | 233.93KB (+120.56KB +106.34%) | 234KB
-- | -- | --
✅ | public/cozy-bar.css | 18.42KB (-5.02KB -21.41%) | 24KB
```

Capture d’écran 2022-03-23 à 10 10 47
7

**Comment by trollepierre** [comment]
Upgrade of cozy-ui@62.2.0


```
  | public/drive.(hash).js | 1.45MB (+155.08KB +11.66%) | 1.47MB
-- | -- | -- | --
```



Capture d’écran 2022-03-23 à 10 17 57

**Review by trollepierre — APPROVED** [review]

**Pull request merged**
