### PR TITLE
doc: help developers with sharing email

### PR DESCRIPTION
**Pull request by enguerran**
Adding some doc about sharing in a development workflow.

We may add some documentation to create two local instances to test master-master share.

### CODE REVIEW

**Comment by enguerran** [comment]
@nono @aenario If you think this documentation could go to the cozy-stack's to enhance it, let me know.

**Comment by enguerran** [comment]
If a real good english speaker could review my english, that'd be great!

**Comment by enguerran** [comment]
you should have suqash both commit into a single one as I did.

**Comment by y-lohse** [comment]
I used the github website to edit the text, so that wasn't an option ¯\_(ツ)_/¯

**Comment by enguerran** [comment]
I am sorry to see your squashed changes not attributed to you. I will put back your extra commit to get it correctly attributed.

**Comment by y-lohse** [comment]
Oh gosh no don't worry about that! I also prefer a clean gitlog over a few typo corrections attributed to me ;)

**Pull request merged**
