### PR TITLE
chore: add cordova to dev dependencies

### PR DESCRIPTION
**Pull request by enguerran**
Two advantages:
1. fix what is the used version
1. do not use global install

### CODE REVIEW

**Comment by ptbrowne** [comment]
IMHO it would be better to specify more precisely (=pin) the cordova version. Otherwise you can have several contributors on different cordova versions and it will lead to difficult to catch bugs.

**Comment by enguerran** [comment]
@ptbrowne if we trust semantic versioning of cordova, there is no risk. Especially if you use `yarn`: https://github.com/cozy/cozy-drive/pull/460/files#diff-8ee2343978836a779dc9f8d6b794c3b2R2070

**Comment by ptbrowne** [comment]
> if we trust semantic versioning of cordova, there is no risk

Exactly, I have been bitten enough by Cordova not to trust them too much :)

**Comment by ptbrowne** [comment]
It is true though that the lock file has the pinned version so we will know if it change. Good for me !

**Comment by enguerran** [comment]
If we want we could upgrade npm to 5+ and use package.json.lock to be more explicit.

**Pull request merged**
