### PR TITLE
feat: Update cozy-client from 34.1.5 to 34.7.1

### PR DESCRIPTION
**Pull request by cballevre**
```
### 🔧 Tech

* Update cozy-client from 34.1.5 to 34.7.1
```

### CODE REVIEW

**Comment by cballevre** [comment]
@Crash-- the increase on https://github.com/cozy/cozy-drive/pull/2815 seems to come from cozy-client update but I don't know why for the moment

**Comment by cballevre** [comment]
@Crash-- maybe this increase come from cozy-client >= 34.4.0 where date-fns has been put as an dependency in 2.29.3 (cc: [bundlephobia](https://bundlephobia.com/package/date-fns@2.29.3), [commit](https://github.com/cozy/cozy-client/commit/c4e392cb161555110f7cdf72ff4900ea33f3f768?diff=unified)). I will check bundlemon if I upgrade cozy-client into `34.3.0`.

**Comment by cballevre** [comment]
@Crash-- seems that the use of resolution don't decrease the bundle size. I propose to remove this work and merge unless you have another track to dig 🤔

**Comment by Crash--** [comment]
Let me quickly check.

**Comment by Crash--** [comment]
```
 yarn why date-fns
yarn why v1.22.18
[1/4] 🤔  Why do we have the module "date-fns"...?
[2/4] 🚚  Initialising dependency graph...
warning Resolution field "date-fns@1.30.1" is incompatible with requested version "date-fns@2.29.3"
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "date-fns@1.30.1"
info Has been hoisted to "date-fns"
info Reasons this module exists
   - Specified in "dependencies"
   - Hoisted from "cozy-client#date-fns"
   - Hoisted from "cozy-ui#date-fns"
   - Hoisted from "cozy-doctypes#date-fns"
   - Hoisted from "cozy-harvest-lib#date-fns"
   - Hoisted from "cozy-harvest-lib#cozy-doctypes#date-fns"
   - Hoisted from "cozy-sharing#cozy-doctypes#date-fns"
info Disk size without dependencies: "4.54MB"
info Disk size with unique dependencies: "4.54MB"
info Disk size with transitive dependencies: "4.54MB"
info Number of shared dependencies: 0
✨  Done in 0.51s.
```

So I only have one date-fns for now. Before, we had two. 

So why the bundle size is not changed? 🤔

**Pull request merged**
