### PR TITLE
fix: Upgrade cozy-ui

### PR DESCRIPTION
**Pull request by y-lohse**
No breaking changes for us because:

- We still use a custom avatar component, so the size changes don't affect us yet
- We don't use the stylesheet from cozy-ui (because I don't think we need it? We import the stuff we really want.)

### CODE REVIEW

**Comment by y-lohse** [comment]
[update cozy-UI](https://trello.com/c/Hz8NcJpL/1674-update-cozy-ui)

**Comment by y-lohse** [comment]
> Does't it also break the Auth screen ? (I upgraded to v18 in my branch and the screens are not centered anymore).

You're right, good catch, it broke the auth screen. @GoOz in https://github.com/cozy/cozy-ui/pull/829#issue-250403112 we changed the wizard alignment on mobile — does this mean some wizard screens must be top-aligned, and others must be centered (like our login screen) ?

**Comment by GoOz** [comment]
Most wizard screens on mobile are top aligned, but some are centered.
Basically I think the rule is: if there's an element with a user interaction such as form elements, it should be top aligned (because of the keyboard), if not then it should be centered.

**Comment by y-lohse** [comment]
Ok thanks! And if we want to center the screen, should we just override the necessary rules? Or are there other classes to use?

**Comment by GoOz** [comment]
Oh yeah sorry I meant to fix that but… well I forgot. You should add the class `.wizard-wrapper--center` to the element with the class `wizard-wrapper`. I think that's pretty much it.

**Pull request merged**
