### PR TITLE
fix: use cozy client and pouch to search for files

### PR DESCRIPTION
**Pull request by y-lohse**
Worked like a charm..? It seems almost to easy.

### CODE REVIEW

**Comment by y-lohse** [comment]
[(3) [DRI] Améliorer les performances de la recherche avec PouchDB](https://trello.com/c/tOTH9FN3/548-3-dri-am%C3%A9liorer-les-performances-de-la-recherche-avec-pouchdb)

**Comment by goldoraf** [comment]
hmmm... you don't use Pouch here, you need to declare an `offline` option to the client

**Comment by y-lohse** [comment]
Mmh ok, I'll investigate more. But somehow the search times are wayyyy down already.

**Comment by y-lohse** [comment]
I'll re-open this once it's ready.

**Pull request closed without merging**
