### PR TITLE
fix: splitFilename() edge cases

### PR DESCRIPTION
**Pull request by sebn**
- Don't assume extension-less filename last char is extension
- Don't confuse hidden file with extension

### CODE REVIEW

**Comment by Crash--** [comment]
Thanks for the PR. We just move our splitFilename method to https://github.com/cozy/cozy-drive/pull/1768/files 

I can take your code and change at the new place if you want.

**Comment by sebn** [comment]
@Crash-- I suppose you mean #1751 ? Don't bother with the rebase, I'll do it :)

**Comment by Crash--** [comment]
Oh right, wrong link... Sorry

This is not just a rebase, we're currently creating our `Model` in cozy-libs/doctypes since we are using more and more functionality outside of our main app. 

So you have to make the PR about splitFileName here : https://github.com/cozy/cozy-libs/blob/master/packages/cozy-doctypes/src/File.js#L81

**Comment by sebn** [comment]
Oops, I missed the different repo. Thanks! I'll move it there, possibly today.

**Comment by sebn** [comment]
Closing in favor of https://github.com/cozy/cozy-libs/pull/684

**Pull request closed without merging**
