### PR TITLE
chore: upgrade jest to v20

### PR DESCRIPTION
**Pull request by enguerran**
jest 20 is very good for promises

### CODE REVIEW

**Comment by enguerran** [comment]
I think tests are outdated.

---

Je ne suis pas vraiment convaincu par les tests en place.

**Comment by nono** [comment]
@goldoraf what do we do about this?

**Comment by enguerran** [comment]
@nono Do I have to wait for @goldoraf 's?

**Comment by enguerran** [comment]
IDK what to do

**Comment by enguerran** [comment]
Maybe we'll reach August 22th to be a 2 months-long Pull Request

**Pull request closed without merging**
