### PR TITLE
Feat/enhanced media backup

### PR DESCRIPTION
**Pull request by GoOz**
- [x] Updated UI to 5.0.2
- [x] Update MediaBackup icon
- [x] Add background-color on MediaBackup
- [x] Display MediaBackup only on root folder

mediabackup

### CODE REVIEW

**Comment by GoOz** [comment]
[(1) 📱 Améliorer le style de l'état de la sauvegarde médias](https://trello.com/c/XnHLM4AY/643-1-%F0%9F%93%B1-am%C3%A9liorer-le-style-de-l%C3%A9tat-de-la-sauvegarde-m%C3%A9dias)

**Comment by GoOz** [comment]
@y-lohse Yes. I didn't do anything special for those views but I think that `ROOT_DIR_ID` matches only the root of the explorer, not trash or recent.

**Comment by y-lohse** [comment]
@GoOz we missed it in the review, but you forgot to update the `yarn.lock` file. Do you mind pushing a fix for that?

**Comment by GoOz** [comment]
@y-lohse oh shit. true. on it!

**Pull request merged**
