### PR TITLE
added a parameter when calling photoLibrary

### PR DESCRIPTION
**Pull request by maestun**
you should use this customized Photo Library plugin:
https://github.com/maestun/cordova-plugin-photo-library

The updated code is in branch « skip_icloud_pics  »

(A pull request is being sent to the maintainer of the plugin)

### CODE REVIEW

**Comment by maestun** [comment]
OK. If the fork solution is chosen, we'd better fork the plugin as a Cozy repo instead of using my junkyard account :)

**Comment by enguerran** [comment]
I am not a big fan of using a fork. If we do, we'll have to maintain it. And to keep track of the changes of the original repository. I don't know how much effort we want to put in cordova plugins maintenance.

**Comment by nono** [comment]
A new version of cordova-plugin-photo-library has been released: [v2.1.0](https://github.com/terikon/cordova-plugin-photo-library/tree/v2.1.0), and it includes the https://github.com/terikon/cordova-plugin-photo-library/pull/74 PR.

**Comment by enguerran** [comment]
@maestun What could we do with this?

**Comment by y-lohse** [comment]
We can close this PR. It's a good blueprint for the work we'll need to do to merge @maestun 's changes, but it's better if we do it ourselves later.

**Pull request closed without merging**
