### PR TITLE
feat(search): fetch only required params for search

### PR DESCRIPTION
**Pull request by trollepierre**
- [ ] Changelog updated if needed

In local, benchmark:

with 11 432 files with 10000 in my trashes. (there are 1059 remaining files in my cozy)

Without optims: 120ms - 9.66Mo
Capture d’écran 2022-08-29 à 15 37 14

With optimisation:  2s - 2.46Mo
Capture d’écran 2022-08-29 à 15 38 51

### CODE REVIEW

**Comment by Crash--** [comment]
Can we have the global time for the user: When I write the word I'm looking for until the results are displayed? 

Having this time for: 
- current status (so with the note fix)
- this PR 
- the previous implementation based on mango query 

Also, can you test on a more realistic cozy, aka : few files in the trash (let's say 100) for 10k docs in total?

**Comment by trollepierre** [comment]
Master:  (all_docs)
master

PR 2679: (all_docs Fields=)
PR 2679

PR 2663: (mango / findAll)
PR 2663

**Review by Crash-- — APPROVED** [review]
I would have preferred numbers, but let's go 👍

**Comment by Crash--** [comment]
I think this PR needs https://github.com/cozy/cozy-client/pull/1230 to work correctly.

**Pull request merged**
