### PR TITLE
feat: add responsive date format

### PR DESCRIPTION
**Pull request by GoOz**
Changes the date format according to the vewport's size. 
1200+ pixels wide means a full written month, otherwise it's an abbreviated one.

### CODE REVIEW

**Comment by GoOz** [comment]
@y-lohse that's prettier I guess. Pretty sure, actually.

**Comment by y-lohse** [comment]
But why does prettier change them *now*? They've been around for a while.

**Comment by GoOz** [comment]
Mmmmh maybe I don't have the same option in my prettier plugin in my editor…

**Comment by enguerran** [comment]
I don't know why this commit https://github.com/cozy/cozy-drive/pull/453/commits/b729ff615d05c504767e41cb8bcc1bba2b2a9937 is failing and I see that the next commit https://github.com/cozy/cozy-drive/pull/453/commits/fc2acd1cf2e482643de95274c489abac6f32837e pass the travis build.

I don't think it's a good thing to have failing commits: every commit must be stable.

**Comment by GoOz** [comment]
It's failing because its dependency was out of date. I always do like that actually but I can change if needed.

**Pull request merged**
