### PR TITLE
 fix: Don't use color var in stylus func

### PR DESCRIPTION
**Pull request by GoOz**
Some cleaning in preparation for a future [release of Cozy-UI](https://github.com/cozy/cozy-ui/pull/641) with color variables as CSS custom properties.

~I couldn't test it because I could make Photos works.~ It works fine :)

~⚠️ Meanwhile if your Photos apps works well, you should consider testing it locally before merging.~

### CODE REVIEW

**Comment by GoOz** [comment]
[Utiliser custom properties sur UI pour la personnalisation](https://trello.com/c/oHPjhtmr/336-utiliser-custom-properties-sur-ui-pour-la-personnalisation)

**Comment by y-lohse** [comment]
Why shouldn't we use the variable in this context?

**Comment by GoOz** [comment]
@y-lohse Because it won't work soon. Future Stylus colors vars will look like this `dodgerBlue: var(--dodgerBlue)`.
Stylus don't treat CSS custom properties as variable so it won't get the hexa color attached to it and so it won't be able to use any buitin color function such as `alpha()`, `darken()` or even `rgba()`.
And we will need those custom properties for brand customisation pruposes.

Apart from that, in this case, the color used in the viewer toolbar background doesn't matter much, it just need to be a dark grey. It doesn't have to be linked to the palette afaik.
I guess you can create your own Stylus var on Photos to replace what I did but so far it would only be used there, so i don't see any benefit.

But if you have some other solution, I'm open to discussion :)

**Comment by GoOz** [comment]
Can it be merged?

**Comment by y-lohse** [comment]
Yes, normally the one who creates the PR merges it :)

**Comment by GoOz** [comment]
@y-lohse oh yeah sorry… every team works differently and I'm having a hard time adjusting myself 😕

**Comment by edas** [comment]
Shouldn't we immediatly give them the 3 CSS variable they need instead of converting to color code now and dd CSS variables later ?

**Pull request merged**
