### PR TITLE
Fix/update mobile onboarding

### PR DESCRIPTION
**Pull request by GoOz**
- [x] Centered welcome page the expeced way
- [x] Update dual field for consistency with the onboarding app

### CODE REVIEW

**Comment by GoOz** [comment]
[(𝐒) [ONB] MEP du nouvel onboarding mobile](https://trello.com/c/DCThDhrq/1003-%F0%9D%90%92-onb-mep-du-nouvel-onboarding-mobile)

**Comment by GoOz** [comment]
[(S) [ONB] MEP du nouveau login](https://trello.com/c/4lLW4oow/1006-s-onb-mep-du-nouveau-login)

**Comment by GoOz** [comment]
Yeah, it deals with the sizing according to available space and the input just fits in it, otherwise it doesn't behave correctly.

**Comment by GoOz** [comment]
@y-lohse Do you know why the CI fails? I don't get it. 
Also should you (the Appvengers) merge it when you think its ready to be merged or should I?

**Comment by Crash--** [comment]
Thank you @GoOz 

Don't worry about our CI, our e2e tests are broken for now ;)

**Pull request merged**
