### PR TITLE
fix: Add loading-placeholder for icon

### PR DESCRIPTION
**Pull request by y-lohse**
Missed the new column on the placeholder view.

### CODE REVIEW

**Comment by y-lohse** [comment]
[Drive décalage labels colonne Taille, Mise à jour](https://trello.com/c/plbiDnSY/1843-drive-d%C3%A9calage-labels-colonne-taille-mise-%C3%A0-jour)

**Comment by Crash--** [comment]
What does it fix?

**Comment by y-lohse** [comment]
Some of the other placeholders were visually offset without this. See [here](https://trello.com/c/plbiDnSY/1843-drive-d%C3%A9calage-labels-colonne-taille-mise-%C3%A0-jour#comment-5ca5bf4a9745c53194c95572) for more details :)

**Comment by cedricmessiant** [comment]
I can't find doc about `withBreakpoints()` on cozy-ui, what are breakpoints ?

**Comment by y-lohse** [comment]
The doc is with the code but not exported, you can find it [here](https://github.com/cozy/cozy-ui/blob/master/react/helpers/withBreakpoints.jsx#L31). They are just like css breakpoints, only meant to be used in js.

**Pull request merged**
