### PR TITLE
fix: Note doesn't have path to compare...

### PR DESCRIPTION
**Pull request by Crash--**
We added a special case recently to handle the
Notes in the search response.

We had to make a call in order to calculte the
url when the user clicks on it since we can't pass
an onClick method ATM, but we forgot to add the
path argument resulting of having a JS error
can't read localCompare of undefined

- [ ] test to add

### CODE REVIEW

**Review by JF-Cozy — COMMENTED** [review]
Il n'y a pas de test associés à modifier ? Ne pourrait-on pas en rajouter ?

**Comment by Crash--** [comment]
> Il n'y a pas de test associés à modifier ? Ne pourrait-on pas en rajouter ?

No test ATM. Few stuff to mock, no time to work on this code. I fixed by opportunity when compiling something else. If this is blocking I can close this PR.

**Review by JF-Cozy — APPROVED** [review]

**Comment by nono** [comment]
@JF-Cozy tu saurais ajouter un test pour ça ?

**Comment by JF-Cozy** [comment]
> @JF-Cozy tu saurais ajouter un test pour ça ?

Je prends enfin le sujet

**Pull request merged**
