### PR TITLE
chore: add more log and check for rundeck script

### PR DESCRIPTION
**Pull request by CozyKourai**
I added some checks and logs

I also add a `sleep 10` before retrying in case of conflicts.
Regarding conflicts, it seems rundeck cannot run the same job at the same time (not depending on the parameters)
there are years-old issues open on that point like https://github.com/rundeck/rundeck/issues/1426 which are still active.

### CODE REVIEW

**Comment by CozyKourai** [comment]
[Mise en place de log sur chaque commande exécutée](https://trello.com/c/YXoieb7N/1805-mise-en-place-de-log-sur-chaque-commande-ex%C3%A9cut%C3%A9e)

**Comment by y-lohse** [comment]
Is this ready for review? If not do you mind putting a WIP label in the PR title until it's ready?

**Comment by Crash--** [comment]
Why  we are not using the stderror to log error trace?

```
myerror=`/mycommand 2>&1 `
echo $myerror 
```

**Comment by CozyKourai** [comment]
[Bug de déploiement ?](https://trello.com/c/6a7tWxBh/1782-bug-de-d%C3%A9ploiement)

**Pull request merged**
