### PR TITLE
fix: Use more color variables

### PR DESCRIPTION
**Pull request by y-lohse**
Replaces some of our hard-coded color codes by variables. The simpler ones.

### CODE REVIEW

**Comment by Crash--** [comment]
Is it just a first pass?

**Comment by y-lohse** [comment]
Yep, these are the "easy" replacements. The remaining ones are new colors, colors with transparency, or generally things that require some thought before being replaced.

**Comment by Crash--** [comment]
Can we change also here : https://github.com/cozy/cozy-drive/blob/master/src/sharing/components/ShareByEmail.jsx#L96 and here https://github.com/cozy/cozy-drive/blob/master/src/sharing/components/ShareByEmail.jsx#L100

**Comment by y-lohse** [comment]
[(2) Codes couleurs en dur](https://trello.com/c/0KjHoPp7/1468-2-codes-couleurs-en-dur)

**Comment by y-lohse** [comment]
I've added the message in our corresponding trello card, we can tackle these colors when we really work on it. i'll merge this in the meantime, even if it's incomplete.

**Pull request merged**
