### PR TITLE
Updated test config

### PR DESCRIPTION
**Pull request by y-lohse**
Creating this PR so we don't forgot about this. Adding tests is currently a pain in the ass, because importing almost any component imports a lot of things and jest can't handle everything. This PR reworks the config until it works, but it's not finished yet.

### CODE REVIEW

**Comment by nono** [comment]
@y-lohse just a friendly reminder that you have this WIP pull request

**Comment by y-lohse** [comment]
Yeah thanks! I'm afraid it will stay like this for a while though, not sure when I (or anyone) will get to work on this again.

**Comment by y-lohse** [comment]
Ok here it is — this new test config should allow us to import pretty much any file in cozy-drive in the test-context without everything crashing horribly.

**Comment by Crash--** [comment]
Cool !

**Pull request merged**
