### PR TITLE
Publish new release

### PR DESCRIPTION
**Pull request by jsilvestre**
This release is a bit peculiar since it's intended to fix production issue on Firefox 52 ESR and Safari.
There are too many bugs on mobile to release the app on the stores, so it's on hold for now.

# Todo
- [x] write the changelog and hand it over the engagement team (PO)
- [x] update the package.json version number (Dev)
- ~~[ ] update the config.xml version number (Dev)~~
- ~~[ ] add the changelog to the mobile folder (Dev)~~
- [ ] merge the release PR (Dev)
- [ ] create git tag (Dev)
- [ ] wait for the build & deploy (PO)
- ~~[ ] publish on Google Play (Dev)~~
- ~~[ ] publish on Apple Store (Dev)~~

# Changelog

### Drive
- Improve recent tab: folder path are now shown
- Add a search bar (not enabled yet)

### Drive
- Amélioration de l'onglet récent : le chemin des dossiers est affiché
- Ajout d'une barre de recherche (pas encore activé)

### CODE REVIEW

**Comment by enguerran** [comment]
[(3) Mettre les applications Drive et Photos dans l'apps registry](https://trello.com/c/Tu30nQwT/557-3-mettre-les-applications-drive-et-photos-dans-lapps-registry)

**Comment by enguerran** [comment]
We'll see if the `publish_registry.sh` script is working from end to end.

**Comment by y-lohse** [comment]
@enguerran can we do something to test the publication ? I don't think the registry is live yet though.

**Comment by y-lohse** [comment]
Do we need to tag the commit *before* we do the merge or something like that?

**Pull request merged**
