### PR TITLE
chore(stylint): Stylint with Cozy config each .styl files in src

### PR DESCRIPTION
**Pull request by trollepierre**
Previously, stylint checks only a folder in src/drive/styles .
Moreover it was not very strict, that is why I follow the recommended configuration of [stylint](https://www.npmjs.com/package/stylint)

### CODE REVIEW

**Comment by trollepierre** [comment]
@Ldoppea @Crash-- @JF-Cozy : I asked you review, because I think we should use one config of stylus in all the projects of Cozy, and I would like your opinion.

**Review by Ldoppea — APPROVED** [review]
Looks good to me

**Comment by Crash--** [comment]
Hmm it seems we already have a shared `.stylintrc`: https://github.com/cozy/create-cozy-app/blob/master/packages/cozy-scripts/template/app/.stylintrc & https://github.com/cozy/create-cozy-app/blob/master/packages/cozy-scripts/config/.stylintrc

**Comment by trollepierre** [comment]
Thanks to Crash, I discover how to use directly Cozy shared config. Fixed done!

**Comment by trollepierre** [comment]
@Crash-- : do you mean the changelog of Drive adding a
```
# 1.39.0
## 🔧 Tech
* Stylint with Cozy config each .styl files in src 
```

isn't it weird to prepublish a changelog of a release not published?

**Comment by Crash--** [comment]
> @Crash-- : do you mean the changelog of Drive adding a

# 1.39.0
## 🔧 Tech
* Stylint with Cozy config each .styl files in src 

Exactly. 

> isn't it weird to prepublish a changelog of a release not published?

We do not publish. It's only on master. So if you take the master, you have all the changes. It makes sens to me.

**Pull request merged**
